-- Basic config
require("core.plugins")
require("core.mappings")
require("core.config")
require("core.colors")

-- Plugins config
require("plugins.neotree")
require("plugins.treesitter")
require("plugins.telescope")
require("plugins.cmp")
require("plugins.mason")
require("plugins.lsp")
require("plugins.autopairs")
require("plugins.comments")
require("plugins.toggleterm")
require("plugins.gitsigns")
require("plugins.lualine")
require("plugins.transparent")
require("plugins.nullls")
require("plugins.column")
require("plugins.nullls")
require("plugins.buffline")
-- require("plugins.lsp_lines")
